import type { TemplateMeta } from "@/lib/resume/types";

export const templateCatalog: TemplateMeta[] = [
  {
    key: "minimal",
    name: "Minimal",
    tagline: "Single-column and built to pass ATS parsers cleanly",
    description:
      "A quiet, single-column layout with no graphics or tables — the safest choice when a resume needs to be read by an applicant tracking system before a person ever sees it.",
    atsFriendly: true,
    style: "simple",
    format: ["ats-friendly", "one-page"],
    experienceLevel: ["student", "entry-level", "experienced"],
    colorSlots: ["accentColor", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
  {
    key: "professional",
    name: "Professional",
    tagline: "A traditional layout with a confident accent divider",
    description:
      "Familiar section order and a restrained accent line under each heading — reads as serious and corporate without feeling dated.",
    atsFriendly: true,
    style: "professional",
    format: ["ats-friendly", "one-page"],
    experienceLevel: ["entry-level", "experienced", "executive"],
    colorSlots: ["accentColor", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
  {
    key: "modern",
    name: "Modern",
    tagline: "A colored header band with room for a skills sidebar",
    description:
      "A header band and optional two-column layout give this template more visual presence — a good fit for design, marketing, and tech roles where some personality is welcome.",
    atsFriendly: false,
    atsNote: "The two-column layout can confuse some ATS parsers — switch to one column in the appearance panel if you're applying somewhere that screens resumes automatically.",
    style: "modern",
    format: ["two-column"],
    experienceLevel: ["entry-level", "experienced"],
    colorSlots: ["accentColor", "headerBg", "linkColor"],
    supportsLayoutToggle: true,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      headerBg: "#eef2fa",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
      layout: "two-column",
    },
  },
  {
    key: "executive",
    name: "Executive",
    tagline: "Centered and formal, built for senior roles",
    description:
      "A fully centered, single-column layout with restrained typography and generous whitespace — reads as senior and deliberate rather than decorative. Common for leadership, legal, and finance resumes.",
    atsFriendly: true,
    style: "professional",
    format: ["ats-friendly", "one-page"],
    experienceLevel: ["experienced", "executive"],
    colorSlots: ["accentColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#1f2937",
      font: "inter",
      fontSize: "medium",
      spacing: "spacious",
    },
  },
  {
    key: "international",
    name: "International",
    tagline: "A photo and sidebar, in the style used across Europe and Asia",
    description:
      "A persistent photo and contact sidebar next to your experience — close to the Europass format expected for many EU public-sector and academic applications, and the norm in much of Europe and Asia more broadly. Most US, UK, and Canadian employers still expect no photo, so switch templates if you're applying there.",
    atsFriendly: false,
    atsNote: "Photos and multi-column layouts are parsed unreliably by ATS software — use Minimal or Professional instead for roles that screen resumes automatically.",
    style: "creative",
    format: ["two-column"],
    experienceLevel: ["student", "entry-level", "experienced"],
    colorSlots: ["accentColor", "headerBg", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      headerBg: "#eef2fa",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
  {
    key: "compact",
    name: "Compact",
    tagline: "Dense and efficient — fits more experience on one page",
    description:
      "Smaller type and tighter spacing than Minimal, built for people with a long work history who still need to fit everything on one page.",
    atsFriendly: true,
    style: "simple",
    format: ["ats-friendly", "one-page"],
    experienceLevel: ["experienced", "executive"],
    colorSlots: ["accentColor", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "small",
      spacing: "compact",
    },
  },
  {
    key: "technical",
    name: "Technical",
    tagline: "Skills up front, in the format engineers expect",
    description:
      "Leads with a tagged skills list and keeps everything else plain and scannable — built for engineering and other technical roles.",
    atsFriendly: true,
    style: "modern",
    format: ["ats-friendly", "one-page"],
    experienceLevel: ["entry-level", "experienced"],
    colorSlots: ["accentColor", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
  {
    key: "academic",
    name: "Academic CV",
    tagline: "Education first, built for research and teaching roles",
    description:
      "Leads with degrees and publications rather than work history, the way academic and research CVs are usually structured. Free to run longer than one page.",
    atsFriendly: true,
    style: "simple",
    format: ["ats-friendly"],
    experienceLevel: ["experienced", "executive"],
    colorSlots: ["accentColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#1f2937",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
  {
    key: "portfolio",
    name: "Portfolio",
    tagline: "Bold typography for creative and design roles",
    description:
      "Larger type and a confident header make this template feel more expressive — built for designers, art directors, and other visual roles.",
    atsFriendly: false,
    atsNote: "Larger, styled headings can parse inconsistently in ATS software — use Minimal or Professional instead for roles that screen resumes automatically.",
    style: "creative",
    format: ["one-page"],
    experienceLevel: ["experienced"],
    colorSlots: ["accentColor", "headerBg", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      headerBg: "#eef2fa",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
  {
    key: "bold",
    name: "Bold",
    tagline: "A full-width color band for a strong first impression",
    description:
      "A bold header band and condensed layout give this template energy — a good fit for fast-moving, early-stage companies.",
    atsFriendly: false,
    atsNote: "The full-width color header can confuse ATS parsers — use Minimal or Professional instead for roles that screen resumes automatically.",
    style: "modern",
    format: ["one-page"],
    experienceLevel: ["entry-level", "experienced"],
    colorSlots: ["accentColor", "headerBg", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      headerBg: "#2563eb",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
  {
    key: "graduate",
    name: "Graduate",
    tagline: "Leads with education and projects, not work history",
    description:
      "Puts your degree and projects ahead of work experience — built for students and recent graduates who don't have much of a work history yet.",
    atsFriendly: true,
    style: "simple",
    format: ["ats-friendly", "one-page"],
    experienceLevel: ["student", "entry-level"],
    colorSlots: ["accentColor", "linkColor"],
    supportsLayoutToggle: false,
    supportsPhoto: true,
    defaultAppearance: {
      accentColor: "#2563eb",
      linkColor: "#2563eb",
      font: "inter",
      fontSize: "medium",
      spacing: "comfortable",
    },
  },
];

export function getTemplateMeta(key: string): TemplateMeta | undefined {
  return templateCatalog.find((t) => t.key === key);
}
